[tool.isort]
profile = 'black'
skip_gitignore = true
src_paths = ['src/clip_benchmark']

[tool.mypy]
python_version = 3.10
ignore_missing_imports = true

[tool.pytest.ini_options]
markers = ["gpu: marks tests requires gpu machine (deselect with '-m \"not gpu\"')"]

[tool.ruff]
exclude = [
    '.eggs',
    '.git',
    '.ipynb_checkpoints',
    '.mypy_cache',
    '.pytest_cache',
    '.ruff_cache',
    '.venv',
    '.vscode',
    '__pypackages__',
    'build',
    'dist',
    'site-packages',
    'venv',
]
line-length = 88
indent-width = 4
target-version = 'py310'

[tool.ruff.lint]
select = ['E4', 'E7', 'E9', 'F']
ignore = []
fixable = ['ALL']
unfixable = []
dummy-variable-rgx = '^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$'

[tool.ruff.format]
quote-style = 'single'
indent-style = 'space'
skip-magic-trailing-comma = false
line-ending = 'auto'
